// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseEchart: typeof import('./src/components/echarts/src/base-echart.vue')['default']
    DeleteModal: typeof import('./src/components/modal/src/DeleteModal.vue')['default']
    EditInput: typeof import('./src/components/editBox/src/EditInput.vue')['default']
    EditSelectMultiple: typeof import('./src/components/editBox/src/EditSelectMultiple.vue')['default']
    EditSelectOne: typeof import('./src/components/editBox/src/EditSelectOne.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
